### ISSUE TITLE
Feature Request: 提议san/order-in-components规则对自定义成员方法进行排序检测

### ISSUE THREAD

**Issue by zhixinbao** [ecomfe/eslint-plugin-san#32]
在该 san/order-in-components 规则下，san 组件中自定义的成员方法在 checkOrder 的排序检测方法中没有相应的处理。
在默认配置下，如有下列属性，排序检测是符合预期的：
`['template', 'initData', 'attached']`
![image](https://user-images.githubusercontent.com/4027710/147639912-01dbf1ba-41da-4a8d-8e7b-63ce0c006f86.png)

但是，当为 san 组件自定义了成员方法，由于 getOrderPosition 方法在 orderMap 中没有记录或配置，那么就不会被正确检测。比如`['template', 'customMethod1', 'customMethod2', 'initData', 'attached']`，示例：
![image](https://user-images.githubusercontent.com/4027710/147640049-88098749-3fc6-4c37-9e33-50a2bb973cb8.png)

主要代码逻辑：
https://github.com/ecomfe/eslint-plugin-san/blob/main/lib/rules/order-in-components.js#L51
https://github.com/ecomfe/eslint-plugin-san/blob/main/lib/rules/order-in-components.js#L221

期望的结果是，开发者自定义的成员方法，应该独立形成一个 `group`，在定义的 `order` 指定位置处参与排序检测，`group` 内部可以支持 `alpabeta` 排序，类似`san/attributes-order`规则。

提议配置规则添加 `CUSTOM_METHODS`，指代自定义的成员方法，示例：
```
{
  "san/order-in-components": ["error", {
    "order": [
      // 视图
      "template",
      "components",
      "trimWhitespace",

      // 事件
      "messages",

      // 数据
      "dataTypes",
      "computed",
      "filters",
      "initData",

      // 生命周期
      "LIFECYCLE_HOOKS",

      // 自定义的成员方法
      "CUSTOM_METHODS"
    ]
  }]
}
```

**Comment by BUPTlhuanyu** [comment]
![image](https://user-images.githubusercontent.com/27213108/147802477-22e63a53-f5da-4004-8239-45613337a659.png)
看着是ok的？

![image](https://user-images.githubusercontent.com/27213108/147802496-a627daba-a145-4ab9-8889-f8d0a99f5f0f.png)
