### ISSUE TITLE
template 中 s-for 中包含 index时会解析报错

### ISSUE THREAD

**Issue by Glen1021** [ecomfe/eslint-plugin-san#6]
![image](https://user-images.githubusercontent.com/75113030/118791940-c3550b80-b8c9-11eb-9c57-b942d8fd9b7a.png)

![image](https://user-images.githubusercontent.com/75113030/118791965-c8b25600-b8c9-11eb-8e8b-64cdf1d11950.png)

**Comment by MBearo** [comment]
@Glen1021 可以用小括号包裹`item,index`

**Comment by MBearo** [comment]
> @Glen1021 可以用小括号包裹`item,index`

看他测试用例得出的结论，然而小括号不符合 san 的语法

**Comment by BUPTlhuanyu** [comment]
> @Glen1021 可以用小括号包裹`item,index`

san 中不支持小括号以及 of 这些操作

**Comment by BUPTlhuanyu** [comment]
目前没看到报错
